### ISSUE TITLE
Needs additional instructions 

### ISSUE THREAD

**Issue by UniversusTech** [derStephan/AdminerPlugins#2]
Seems a very useful plugin, simply needs some info on how to "unhide" for the hideableColumns plugin.

**Comment by derStephan** [comment]
Thank you for the suggestion. 

You can not unhide single columns. You have to start over again with "select data". This follows the same concept as for adminer's search fields. Just start over. 

What you can do is removing the respective hide parameter from the URL. But I don't think that is what you had in mind. Sorry.
