### ISSUE TITLE
hideableColumns doesn't work

### ISSUE THREAD

**Issue by mattymatty76** [derStephan/AdminerPlugins#3]
Hi, unfortunately this plugin doesn't work: I have tried a lot and several way: firefox, edge, chrome all last version and of course Adminer 4.8.1 but nothing...
Are you sure it works?
In any case thank you for your work and support

**Comment by derStephan** [comment]
Hi,
I am pretty sure it works, I am using it every day. Can you show me how you included the plugin and give a detailed description of what you are doing and what is not working?

Thanks

**Comment by mattymatty76** [comment]
Yes of course...
I'm using Adminer Bootstrap-Like Design and the steps I have followed are these:

1) I have put hideableColumns.php inside plugin/ directory

2) I have add this code in function adminer_object() {

$plugins = array(
        // specify enabled plugins here
        new AdminerSlugify,
        new AdminerEditTextarea,
        new AdminerEditForeign,
        new AdminerEnumOption,
        new AdminerTableStructure,
        new AdminerTableIndexesStructure,
        new AdminerDumpJson,
        new AdminerDumpZip,
        new hideableColums
    );

3) I have tried to click, holding ALT-key, over the header label

but doesn't work, I don't know where I'm wrong

thank you for your answare

**Comment by derStephan** [comment]
Thank you for the answer. May I ask you to disable all other plugins and just try it with my plugin only? If it works then, another plugin stops adminer from calling the right function. We had [the same problem](https://github.com/derStephan/AdminerPlugins/issues/1#issuecomment-1231387264) before. 

If this works, move my plugin to the very top of $plugins to be called before adminer is stopped. 

Please note, that the plugin will only work in "select data" view.

**Comment by derStephan** [comment]
By the way, did you see that there is a typo in your definition of $plugins. The _**n**_ in ColumNs is missing.

**Comment by derStephan** [comment]
Sorry, the typo is in my documentation. Fixed it. Sorry for the inconvenience.

**Comment by mattymatty76** [comment]
don't worry, if there is someone that should say "sorry" that it's me: because I give you more job to do...
I will try your tips about to use your plugin only...
thank you

**Comment by mattymatty76** [comment]
nothing, same result, I have put only hideableColumns plugin and removed all others but in my case not works

**Comment by derStephan** [comment]
Did you change the typo in your definition of $plugins?

The n in Colum**_N_**s is missing.

**Comment by mattymatty76** [comment]
Yes I did, but unfortunately it doesn't work :(
but maybe I'm wrong something, because if you can use it without problem as well as other people; the problem is mine.
When I click over (in select view mode) an header label in firefox nothing is appening, while chrome gives me the download page...
Thank you, I've done to you wasted too much time

**Comment by derStephan** [comment]
Please, by all means... let us fix this for you! I am happy to help.

Can you show me the current definition of $plugins, please?

This works for me: 
`$plugins = array(
       	new hideableColumns()
    );`

**Comment by mattymatty76** [comment]
Yes absolutely, thank you

this is the file called plugin.php inside adminer/adminer/plugin.php

`<?php
function adminer_object() {
	// required to run any plugin
	include_once "../plugins/plugin.php";
	
	// autoloader
	foreach (glob("../plugins/*.php") as $filename) {
		include_once $filename;
	}
	
	$plugins = array(
		// specify enabled plugins here
		new AdminerDatabaseHide(array('information_schema')),
		new AdminerDumpJson,
		new AdminerDumpBz2,
		new AdminerDumpZip,
		new AdminerDumpXml,
		new AdminerDumpAlter,
		new AdminerFileUpload(""),
		new AdminerJsonColumn,
		new AdminerSlugify,
		new AdminerTranslation,
		new AdminerForeignSystem,
		new AdminerEnumOption,
		new AdminerTablesFilter,
		new AdminerEditForeign,
	        new hideableColumns,
	);
	
	return new AdminerPlugin($plugins);
}
include "./index.php";`




inside adminer/plugins/ I've copied your file hideableColumns.php

note: I've tried to put new hideableColumns above the others and another test (what you told me) where I put it alone

**Comment by derStephan** [comment]
looks right to me. May I ask you to open Javascript console in browser (using F12) and there go to console. Hold alt-key and click on the name of a column. If there is any entry in console, please paste that here.

**Comment by mattymatty76** [comment]
you are right, there isn't any entry in console...

**Comment by derStephan** [comment]
Well, this all seems fishy. May I ask you to do the following? 

1. open hideableColumns.php in an editor
2. add `alert("running");` to line 52
3. save it
4. reload adminer

If my plugin is included at all, it should give you a text box with the text "running". If not, the plugin is not included at all. But again, check the console to be sure.

**Comment by mattymatty76** [comment]
nothing, it doesn't show anything...
seems it's not loading hideableColumns

**Comment by derStephan** [comment]
ok, try putting a ´die("loaded");´ in the very first row of hideableColumns.php and reload adminer. 

If it is loaded, it should be a blank page, showing nothing or "loaded". 

If it is not loaded, there is something wrong with your folder structure or anything else. Did you check the error.log of your webserver? PHP errors are given there.

**Comment by mattymatty76** [comment]
it's the same, it doesn't show nothing, but the strange thing is that I downloaded a new adminer instance 4.8.1 to be sure working on the clean version and not a compromised version and after that, I have followed the same steps that you use when add a plugin: in this case hideableColumns

**Comment by derStephan** [comment]
Ok, so the plugin is not included. Let's investigate that. 

Open adminer/adminer/plugin.php in editor and change 

```
foreach (glob("../plugins/*.php") as $filename) {
	include_once $filename;
}
```

to 

```
echo "begin<br>";
foreach (glob("../plugins/*.php") as $filename) {
	echo $filename."<br>";
}
echo "end<br>";
die();
```

Now call adminer again. This should give you all the files that are in your plugin directory. If this is empty, please check if you call the right file. You have to call the file that includes the plugins. just calling adminer.php will not work.

**Comment by mattymatty76** [comment]
begin
../plugins/colorfields.php
../plugins/database-hide.php
../plugins/designs.php
../plugins/dump-alter.php
../plugins/dump-bz2.php
../plugins/dump-date.php
../plugins/dump-json.php
../plugins/dump-php.php
../plugins/dump-xml.php
../plugins/dump-zip.php
../plugins/edit-calendar.php
../plugins/edit-foreign.php
../plugins/edit-textarea.php
../plugins/email-table.php
../plugins/enum-option.php
../plugins/enum-types.php
../plugins/file-upload.php
../plugins/foreign-system.php
../plugins/frames.php
../plugins/hideableColumns.php
../plugins/json-column.php
../plugins/login-ip.php
../plugins/login-otp.php
../plugins/login-password-less.php
../plugins/login-servers.php
../plugins/login-sqlite.php
../plugins/login-ssl.php
../plugins/login-table.php
../plugins/master-slave.php
../plugins/plugin.php
../plugins/pretty-json-column.php
../plugins/slugify.php
../plugins/sql-log.php
../plugins/struct-comments.php
../plugins/table-indexes-structure.php
../plugins/table-structure.php
../plugins/tables-filter.php
../plugins/tinymce.php
../plugins/translation.php
../plugins/version-noverify.php
../plugins/wymeditor.php
end

**Comment by mattymatty76** [comment]
maybe there is a problem in 

return new AdminerBootstrapLike($plugins);

**Comment by mattymatty76** [comment]
this is the file that I'm manipulating and not works


```
function adminer_object() {
    // required to run any plugin
    include_once "../plugins/plugin.php";
    include_once "../plugins/adminerbootstrap/AdminerBootstrapLike.php";
    
    // autoloader
    foreach (glob("../plugins/*.php") as $filename) {
        include_once "./$filename";
    }
    
    $plugins = array(
        new hideableColumns,
        new AdminerSlugify,
        new AdminerEditTextarea,
        new AdminerEditForeign,
        new AdminerEnumOption,
        new AdminerTableStructure,
        new AdminerTableIndexesStructure,
        new AdminerDumpJson,
        new AdminerDumpZip,
        new AdminerColorfields,
        new AdminerVersionNoverify,
        //new FCSqliteConnectionWithoutCredentials,
        //new AdminerSqlLog,
    );
    
    /* It is possible to combine customization and plugins:
    class AdminerCustomization extends AdminerPlugin {
    }
    return new AdminerCustomization($plugins);
    */
    
    //return new AdminerPlugin($plugins);
    
    return new AdminerBootstrapLike($plugins);
    
}

// include original Adminer or Adminer Editor
include "./index.php";
```

**Comment by mattymatty76** [comment]
but if I change the file in this manner, now work

```
function adminer_object() {
    // required to run any plugin
    include_once "../plugins/plugin.php";
    //include_once "../plugins/adminerbootstrap/AdminerBootstrapLike.php";
    
    // autoloader
    foreach (glob("../plugins/*.php") as $filename) {
        include_once "./$filename";
    }
    
    $plugins = array(
        new hideableColumns,
        new AdminerSlugify,
        new AdminerEditTextarea,
        new AdminerEditForeign,
        new AdminerEnumOption,
        new AdminerTableStructure,
        new AdminerTableIndexesStructure,
        new AdminerDumpJson,
        new AdminerDumpZip,
        new AdminerColorfields,
        new AdminerVersionNoverify,
        //new FCSqliteConnectionWithoutCredentials,
        //new AdminerSqlLog,
    );
    
    /* It is possible to combine customization and plugins:
    class AdminerCustomization extends AdminerPlugin {
    }
    return new AdminerCustomization($plugins);
    */
    
    return new AdminerPlugin($plugins);
    
    //return new AdminerBootstrapLike($plugins);
    
}

// include original Adminer or Adminer Editor
include "./index.php";

```

**Comment by mattymatty76** [comment]
I actually just changed this

```
//include_once "../plugins/adminerbootstrap/AdminerBootstrapLike.php";
...
...
...
return new AdminerPlugin($plugins);
    
//return new AdminerBootstrapLike($plugins);
```

so the problem, I think, is not your plugin but AdminerBootstrapLike.php

**Comment by derStephan** [comment]
Ok. I am glad, it works. But what is that?
>`return new AdminerBootstrapLike($plugins);`

In your example before, you stated the following:

>`return new AdminerPlugin($plugins);`

I thought, you tried a fresh adminer file without anything else to see if it is working. 

No offence, pal. But if you had shown the real source code from the beginning, we could have saved some grey hairs for us. 

I will close this ticket now, as it is working as expected when you are doing what the official manual says, right? Good look.

**Comment by mattymatty76** [comment]
yes yes but at the beginning I did try with the original / new adminer instance and didn't work too, now I have changed with the last code and I have noted that... I don't know if it's a solution, moreover I have tried also with new instance and put at the beginning your plugin now works... maybe a cache problem boh
sorry for grey hairs :(
if you send to me a paypal address I pay you a coffee at leat that

**Comment by derStephan** [comment]
>sorry for grey hairs 

Don't worry, just make sure you give a full and correct example the next time. I have more good plugins that might be interesting for you :-). In my opinion, the most helpful is [searchAutocomplete](https://github.com/derStephan/AdminerPlugins/blob/master/searchAutocomplete.php). I would love to get your opinion on this one. 

>if you send to me a paypal address I pay you a coffee at leat that

You really don't have to. If you want to do good, give that money to a charity of your choice. I am happy that it is working now. Do you open a new ticket for AdminerBootstrapLike? 

Have fun, stay safe.

**Comment by mattymatty76** [comment]
Thank you very much, absolutely, you are right: I've tried several examples in addition to the original version...
I will do... and I will try searchAutocomplete too, but before I'll change my machine to avoid the same problem :D

thanks

**Comment by mattymatty76** [comment]
Excuse me the last thing, I have noted this code inside hideableColumns

```
function headerSpanClick(e)
{
	if(event.altKey)
		window.location.href = '?<?php echo $_SERVER["QUERY_STRING"]?>&hide[]='+event.target.innerText;
}
```

is it correct event.altKey or should be e.altKey

thank you

**Comment by derStephan** [comment]
You are right. This could be better. However, `event` is global and works anyway.

**Comment by mattymatty76** [comment]
sorry I promise you to leave you in pace, but in the last commit 

```
if(e.altKey)
	window.location.href = '?<?php echo $_SERVER["QUERY_STRING"]?>&hide[]='+event.target.innerText;
```

I think, I don't know, it's the same for event.target.innerText; 

thank you

**Comment by derStephan** [comment]
I should not do such things in a rush. I fixed it now. By the way, where did your last message go? I answered but it is gone.

**Comment by mattymatty76** [comment]
I was wrong, I don't know how can I recovery it...
It's strange that you can't recover a message if you click wrong

**Comment by derStephan** [comment]
Don't worry. It's fixed now. Thank you for investigating it. If you find anything else, please share it with me. Please open one ticket for each issue seperately.

**Comment by mattymatty76** [comment]
Great men and great plugin thank you: deserve the best
