### ISSUE TITLE
document downloaded when hiding column in blink engine

### ISSUE THREAD

**Issue by mattymatty76** [derStephan/AdminerPlugins#4]
Hi,
if you use chrome or edge (releated to hideableColumns) when click over link the browser opens/downloads the page; so if you want to avoid it, change...

from

if(e.altKey)
           window.location.href = '?<?php echo $_SERVER["QUERY_STRING"]?>&hide[]='+e.target.innerText;

to

if(e.altKey){
	e.stopPropagation()
	e.preventDefault();
	window.location.href = '?<?php echo $_SERVER["QUERY_STRING"]?>&hide[]='+e.target.innerText;
}

thank you

**Comment by derStephan** [comment]
fixed. I did some testing. e.preventDefault(); does the trick. 

Thank you for your help.
